language: java
jdk:
  - oraclejdk8
sudo: false
install:
-  |
    cat <<EOF

    Running build with the following parameters

    MVN_GOAL=${MVN_GOAL}
    VERSION=${VERSION}
    MILESTONE=${MILESTONE}
    MVN_PROFILE=${MVN_PROFILE}

    EOF
script:
- './mvnw -s .settings.xml $MVN_GOAL $MVN_PROFILE -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - MVN_GOAL="clean install"
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - MILESTONE=$(echo ${VERSION} | egrep 'M|RC' && echo true || echo false)
  - MVN_PROFILE=$([ "${MILESTONE}" == "true" ] && echo -P milestone)
  - TERM=dumb

